### ISSUE TITLE
TS05-DevelopmentTechniques

### ISSUE THREAD

**Issue by maugustoo** [fga-gpp-mds/2017.2-Receituario-Medico#13]
**TS05** - Eu, como desenvolvedor, desejo aplicar as técnicas de programação para garantir uma melhor manutenabilidade do código.

**Critérios de aceitação:**

- [x] Todos os atributos e variáveis devem seguir as regras da [folha de estilo](https://github.com/fga-gpp-mds/2017.2-Receituario-Medico/wiki/Folha-de-Estilo#1-nomea%C3%A7%C3%A3o).
- [x] O código deve estar formatado seguindo a folha de estilo [folha de estilo](https://github.com/fga-gpp-mds/2017.2-Receituario-Medico/wiki/Folha-de-Estilo#2-formata%C3%A7%C3%A3o).
- [x] Aplicar comentários em todas as classes, seguindo a [folha de estilo](https://github.com/fga-gpp-mds/2017.2-Receituario-Medico/wiki/Folha-de-Estilo#3-coment%C3%A1rios).
- [x] Em todos os testes deve se usar assertRaisesMessage() em vez de assertRaises() para que a mensagem de exceção possa ser checada.
- [x] Os _imports_ devem ser separados conforme a [folha de estilo](https://github.com/fga-gpp-mds/2017.2-Receituario-Medico/wiki/Folha-de-Estilo#5-imports).
- [x] Todas os _templates_ devem seguir o estilo definido na [folha de estilo](https://github.com/fga-gpp-mds/2017.2-Receituario-Medico/wiki/Folha-de-Estilo#6-estilo-do-template).
- [x] Todas as _views_ devem seguir o estilo definido na [folha de estilo](https://github.com/fga-gpp-mds/2017.2-Receituario-Medico/wiki/Folha-de-Estilo#7-estilo-da-view).
- [x] Todas as _models_ devem seguir o estilo definido na [folha de estilo](https://github.com/fga-gpp-mds/2017.2-Receituario-Medico/wiki/Folha-de-Estilo#8-estilo-da-model).
- [x] Todas as estruturas de decisão devem seguir o padrão da [folha de estilo](https://github.com/fga-gpp-mds/2017.2-Receituario-Medico/wiki/Folha-de-Estilo#10-estruturas-de-decis%C3%A3o).
- [ ] Todas as classes devem ter **90%** de cobertura, no **mínimo**.
- [ ] Refatorar as classes identificadas como **regular** ou **preocupante** no [relatório da coleta II](https://github.com/fga-gpp-mds/2017.2-Receituario-Medico/wiki/Coleta-II#41-resultados) de modo que a métrica 6 e 7 dos objetivo 02 do [plano de gerenciamento de qualidade](https://github.com/FGA-MED/MedeMais_2017-2/wiki/M%C3%A9tricas#m%C3%A9tricas-objetivo-02-c%C3%B3digo-fonte) seja classificada como excelente ou boa.
